### PR TITLE
ReadME.md

### PR DESCRIPTION
**Pull request by EmanAbdelmeguidAhmed**
I have created a README.md file. Please check it, and let me know if any update is needed.

### CODE REVIEW

**Review by garzarobm — CHANGES_REQUESTED** [review]
Lots of changes needs to be made to the structure of the markdown file. 

For example:
- Please make sure to format list items with '-'
- Ensure all titles are properly prepended with '#'
- All numbered list have a period to signify markdown syntax. I went ahead and started corrections to show you the correct syntax. 

Please fix the remaining document and we will go from there.

See my example below for reference...
#
# Welcome to Smart Vision Project!

## Introduction:

This is a computer vision project that uses a Raspberry Pi and a camera to detect objects in real-time. The project is built using Python and OpenCV. The project is open-source and you can find the code on this GitHub page as more features get added. We tried to build this project differently to be more useful as much as we can. We are open for any suggestion or questions, so please don't hesitate to contact us anytime.



## Table of Contents:

- [Welcome to Smart Vision Project!](#welcome-to-smart-vision-project)
  - [Introduction:](#introduction)
  - [Table of Contents:](#table-of-contents)
  - [Contributing:](#contributing)



## Contributing: 

Thank you for contributing to our project which will help us improve it. You can contribute with us following the below guide: 

- For reporting bugs: 


    1.	Check the existing issues: go to issues tab (link found in links section), if there is any for same bug, please add commit, if not, please follow the below:

    2. Open a New Issue: Click on the "Issues" tab. Then click the "New issue" button,usually located to the right side of the page.

    3. Fill out the issue: add the bug info with clear details. And please make sure to add bug report in the title of the issue.

    4. Submit the issue: click on "submit new issue" button.
 



 > Finish README.md file ...
 > Finish README.md file ...

**Comment by EmanAbdelmeguidAhmed** [comment]
I updated the README.md on my fork with the above requested structure. Please check, and let me know if any further updates are needed.

**Comment by garzarobm** [comment]
It is still missing the format as requested, I am currently reading this as readme:

"Welcome to Smart Vision Project!

Introduction:

This is a computer vision project that uses a Raspberry Pi and a camera to detect objects in real-time. The project is built using Python and OpenCV. The project is open-source and you can find the code on this GitHub page as more features get added. We tried to build this project differently to be more useful as much as we can. We are open for any suggestion or questions, so please don't hesitate to contact us anytime.

Contributing: 

Thank you for contributing to our project which will help us improve it. You can contribute with us following the below guide: 

o For reporting bugs: 

1-	Check the existing issues: go to issues tab (link found in links section), if there is any for same bug, please add commit, if not, please follow the below:

2- Open a New Issue: Click on the "Issues" tab. Then click the "New issue" button,usually located to the right side of the page.

3- Fill out the issue: add the bug info with clear details. And please make sure to add bug report in the title of the issue.

4- Submit the issue: click on "submit new issue" button.

o For requesting features: 

1-	Check the existing issues: go to issues tab (link found in links section), if there is any request for feature, please add commit, if not, please follow the below:

2-	Open a New Issue: Click on the "Issues" tab. Then click the "New issue" button, usually located to the right side of the page.

3-	Fill out the issue: add the feature info with clear details. And please make sure to add feature request in the title of the issue.

o For submitting pull requests: 

- Fork the Repository:

1- Go to our repository (https://github.com/Robjects-ML/SmartVision).

2- Fork the Repository: Click the "Fork" button at the top right corner of the repository page. This will create a copy of the repository under your GitHub account.

3-	Clone your fork: 

Clone the Repository: Clone your forked repository to your local machine. In the terminal or Git Bash, 
run: git clone https://github.com/your-username/repo-name.git Create new branch:

*Replace your-username with your GitHub username and repo-name with the name of the repository.

-	Create new branch:

You can do that by running: git checkout -b your-branch-name 

*Replace your-branch-name with a descriptive name for your branch.

- Start changes:

1-	Edit the Files: Make the necessary changes to the required files.

2-	Stage the Changes: Add the changes to the staging area: by running this code on the terminal or Git Bash: 
git add.

3-	 Commit the Changes: Commit your changes with a descriptive message: run this code: 
git commit -m "Describe your changes". 

4-	Push the changes to GitHub: by running this code in the Terminal or Git Bash: git push origin your-branch-name 

*Replace your-branch-name with the given name for your branch. 

o	Create your Pull Request:

1- Go to your forked repository on GitHub.

2- Open a new Pull Request: go to "Pull Request" tab, and then click "New Pull Request" button.

3- Choose a base and compare branches: on the top left you will find drop down lists for base and compare branches, you will choose the base one as the original repository and the base branch is the branch you want to merge into. The compare branch should be the branch you just pushed.

4- Create a Pull Request by clicking "Create Pull Request" button.

5- Fill Out the Pull Request Form: Provide a title and description for your pull request. Explain what changes you made and why.
Submit the Pull Request by clicking the "Create pull request" button to submit.

Links:

•	Code of conduct document: ……. 

•	YouTube channel: …… 

•	Issues: https://github.com/Robjects-ML/SmartVision/issues

•	Pull Requests: https://github.com/Robjects-ML/SmartVision/pulls

License: 

Please check this link: (https://github.com/Robjects-ML/SmartVision/blob/main/LICENSE.md)

Acknowledgements: 

SmartVision project is built from team members “Eman, Alaa and John” guided by “Mike”. 

GitHub accounts for team members and leader:

 Eman:EmanAbdelmeguidAhmed (team member)
 
John: Geomatic13 (team member)

Alaa: ....  (team member)

Mike: garzarobm (Leader)
"

This lacks the correct structure

**Review by garzarobm — APPROVED** [review]

**Review by garzarobm — APPROVED** [review]

**Review by garzarobm — APPROVED** [review]

**Comment by garzarobm** [comment]
looks good as of now, but I need to figure out how to merge the page

**Pull request merged**
